#!/bin/bash
ls -al

echo "Running the packegjgjggr script now..!!"
change:hii this is change
echo .
echo .jhgjhfghfghdggdgfdgfhgfhgfhgjjgkjkhjj
packer build packer.json bdjjkfg

echo .kjhjgjgjgjhgjhgjgjhgjhgjgjgjgsunnnyyy
echo .snkldfkkj
terraform init
terraform apply --var-file test.tfvars -var 'aws_access_key=AKIAWPGZFNAFKATV32P5' -var 'aws_secret_key=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' --auto-approve
echo "Infra Built Sucessfully....!!!"
docker -H 10.1.1.220 run --rm -dit --name nginx1 --hostname nginx1 -p 8000:80 nginx:latest
